- package.json
- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
- packages/react-bootstrap-table2/test/cell.test.js
- packages/react-bootstrap-table2/test/row.test.js
Implement #12
User can use `column.formatter` to custom their cell and take `column.formatExtraData` to use in formatter function when they need some extra data.
```js
const columns = [{
dataField: 'id',
text: 'Product ID'
}, {
dataField: 'name',
text: 'Product Name',
formatExtraData: ....,  // it's option and allow any data
formatter: (cell, row, rIndex, extraData) =>
(<h3>{ cell }</h3>)
}, {
dataField: 'price',
text: 'Product Price'
}];
<BootstrapTable keyField="id" data={ products } columns={ columns } />
```
> Implement column formatter

- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/src/utils.js
- packages/react-bootstrap-table2/test/utils.test.js
Implement https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/14
it's able to configure the `dataField` to access the nested data, 
```js
const columns = [{
dataField: 'id',
text: 'Person ID'
}, {
dataField: 'nest.address.road',
text: 'Road Name'
}, {
dataField: 'nest.postal',
text: 'Postal'
}];
```
Issue related with https://github.com/AllenFang/react-bootstrap-table/issues/50
`react-bootstrap-table2` will start support nested data from `v0.0.1`.
> Support nested data

- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/src/utils.js
- packages/react-bootstrap-table2/test/cell.test.js
Implement https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/19
It's able to custom the style and class with a static value or a callback function:
```js
{
dataField: 'id',
text: 'Product ID',
style: {
backgroundColor: 'red'
},
classes: 'my-xxx'
}, {
dataField: 'name',
text: 'Product Name',
style: (cell, row, colIndex) => {
// return your style object
},
classes: (cell, row, colIndex) => {
// return your class string
}
}
```
@Chun-MingChen
> Implement custom style/class on cell

- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/test/header-cell.test.js
Implement #26 
```js
column.headerFormatter = (column, colIndex) =>
(<h3>{ column.text }</h3>)
```
> Implement formatter for header column

- docs/columns.md
- packages/react-bootstrap-table2-example/examples/columns/column-align-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-attrs-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-class-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-style-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-title-table.js
- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/test/cell.test.js
#56 
1. re-define cell callback to allow user to pass 4 arguments `cell`, `row`, `rowIndex`, `colIndex`.
2. re-structure document and write in more detail
> Development/redefine cell callback (#56)

- CONTRIBUTING.md
- docs/development.md
Fix typos and misspellings in documentation for development setup
> Improve development setup experience by fixing misspelled areas

- packages/react-bootstrap-table2-example/examples/cell-edit/cell-level-editable-table.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/test/editing-cell.test.js
- packages/react-bootstrap-table2/test/test-helpers/productGenerator.js
Hi @AllenFang , added simple example with callback function in editable, this add onClick/dbClick on cell where num > 2101. In example callback function have three params (text of cell, row, column), what other parameters are needed??
> Implement editable as callback

- .travis.yml
The PR is a little patch to ignore unnecessary `postinstall` in `CI mode`. Besides, install node modules in yarn.
* ref: [#61](https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/61)
> yarn install for CI mode

- docs/README.md
- docs/cell-edit-prop.md
- packages/react-bootstrap-table2-example/examples/cell-edit/cell-edit-with-promise-table.js
- packages/react-bootstrap-table2-example/examples/cell-edit/cell-edit-with-redux-table.js
- packages/react-bootstrap-table2-example/package.json
- packages/react-bootstrap-table2-example/src/index.js
- packages/react-bootstrap-table2-example/src/utils/common.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/cell-edit-wrapper.js
- packages/react-bootstrap-table2/src/editing-cell.js
- packages/react-bootstrap-table2/src/props-resolver/index.js
- packages/react-bootstrap-table2/src/stateful-layer.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/src/utils.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
- packages/react-bootstrap-table2/test/cell-edit-wrapper.test.js
- packages/react-bootstrap-table2/test/editing-cell.test.js
- packages/react-bootstrap-table2/test/props-resolver/index.test.js
- packages/react-bootstrap-table2/test/row.test.js
- packages/react-bootstrap-table2/test/stateful-layer.test.js
- packages/react-bootstrap-table2/test/test-helpers/mock-component.js
#63 
* Support Cell Editing with Promise
* Support Cell Editing with Redux way(A little complicated, I'll keep to figure if we can simply it)
Some things need to change after merging this PR:
1. Refine `stateful-layer.js`
2. Implement a wrapper for sorting
3. Fix promise hard to test problem
> Implement async cell edit

- packages/react-bootstrap-table2/src/cell-edit/wrapper.js
- packages/react-bootstrap-table2/src/container.js
- packages/react-bootstrap-table2/src/row-selection/wrapper.js
- packages/react-bootstrap-table2/src/sort/wrapper.js
- packages/react-bootstrap-table2/src/table-factory.js
- packages/react-bootstrap-table2/test/cell-edit/wrapper.test.js
- packages/react-bootstrap-table2/test/container.test.js
- packages/react-bootstrap-table2/test/row-selection/wrapper.test.js
- packages/react-bootstrap-table2/test/sort/wrapper.test.js
@Chun-MingChen 
Sorry that I make a mistake about `React.cloneElement`..  I expect to use `React.cloneElement` to wrap the element again and again for the reason of separating the heavy logic to different and small components.
So I defined the three wrapper: 
`./packages/react-bootstrap-table2/src/sort/wrapper.js`
`./packages/react-bootstrap-table2/src/row-selection/wrapper.js`
`./packages/react-bootstrap-table2/src/cell-edit/wrapper.js`
And in the `render` method of `./packages/react-bootstrap-table2/src/container.js`, I use `React.cloneElement` to wrap a react element dynamically(I mean it depend on props that user given) 
Actually all of those stuff is work until I found a bug when we render with one more wrappers, 
for example, if user define a table with sort and row selection or
a …
> Fix wrong higher order wrapping

- packages/react-bootstrap-table2-example/.storybook/addons.js
- packages/react-bootstrap-table2-example/.storybook/config.js
- packages/react-bootstrap-table2-example/package.json
#117 
This PR aims to print all console messages to `logger panel` with  [storybook-addon-console](https://github.com/storybooks/storybook-addon-console). Please refer to the pic below. So far it will print all the messages including `eslint` warning or something like that. If we wanna focus on the messages excluding system warning, we could add exclusive rule to ignore in the future.
> logs messages on the story panel (#117)

- docs/README.md
I forgot to add docs for pagination...
> docs for pagination

- packages/react-bootstrap-table2-paginator/src/index.js
- packages/react-bootstrap-table2-paginator/src/wrapper.js
- packages/react-bootstrap-table2-paginator/test/wrapper.test.js
- packages/react-bootstrap-table2/src/table-factory.js
- packages/react-bootstrap-table2/test/container.test.js
Fix lifecycle issue due to HOC
> fix liftcycle issue

- docs/README.md
- packages/react-bootstrap-table2-example/examples/remote/remote-all.js
- packages/react-bootstrap-table2-example/examples/remote/remote-filter.js
- packages/react-bootstrap-table2-example/examples/remote/remote-pagination.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-filter/src/wrapper.js
- packages/react-bootstrap-table2-filter/test/wrapper.test.js
- packages/react-bootstrap-table2-paginator/src/wrapper.js
- packages/react-bootstrap-table2-paginator/test/wrapper.test.js
- packages/react-bootstrap-table2/src/container.js
- packages/react-bootstrap-table2/src/store/index.js
- packages/react-bootstrap-table2/test/container.test.js
I will have some refactoring after this PR.
> Implement remote filter

- docs/columns.md
- docs/migration.md
- gulpfile.babel.js
- packages/react-bootstrap-table2-example/.storybook/webpack.config.js
- packages/react-bootstrap-table2-example/examples/column-filter/custom-select-filter.js
- packages/react-bootstrap-table2-example/examples/column-filter/select-filter-default-value.js
- packages/react-bootstrap-table2-example/examples/column-filter/select-filter-like-comparator.js
- packages/react-bootstrap-table2-example/examples/column-filter/select-filter.js
- packages/react-bootstrap-table2-example/src/utils/common.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-filter/README.md
- packages/react-bootstrap-table2-filter/index.js
- packages/react-bootstrap-table2-filter/src/components/select.js
- packages/react-bootstrap-table2-filter/src/const.js
- packages/react-bootstrap-table2-filter/src/wrapper.js
- packages/react-bootstrap-table2-filter/style/react-bootstrap-table2-filter.scss
- packages/react-bootstrap-table2-filter/test/components/select.test.js
- packages/react-bootstrap-table2/test/row-selection/selection-cell.test.js
> Select filter

- docs/migration.md
- packages/react-bootstrap-table2-example/examples/column-filter/custom-number-filter.js
- packages/react-bootstrap-table2-example/examples/column-filter/number-filter-default-value.js
- packages/react-bootstrap-table2-example/examples/column-filter/number-filter.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-filter/README.md
- packages/react-bootstrap-table2-filter/index.js
- packages/react-bootstrap-table2-filter/src/comparison.js
- packages/react-bootstrap-table2-filter/src/components/number.js
- packages/react-bootstrap-table2-filter/src/const.js
- packages/react-bootstrap-table2-filter/src/filter.js
- packages/react-bootstrap-table2-filter/style/react-bootstrap-table2-filter.scss
- packages/react-bootstrap-table2-filter/test/components/number.test.js
- packages/react-bootstrap-table2-filter/test/filter.test.js
> Implement number filter

- packages/react-bootstrap-table2-example/examples/column-filter/custom-text-filter.js
- packages/react-bootstrap-table2-filter/src/components/text.js
- packages/react-bootstrap-table2-filter/src/filter.js
- packages/react-bootstrap-table2-filter/src/wrapper.js
> case insensitive text filter

- packages/react-bootstrap-table2-example/examples/basic/customized-id-classes.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-example/stories/stylesheet/base-table/_index.scss
- packages/react-bootstrap-table2-example/stories/stylesheet/storybook.scss
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
fix #235 
This PR aims to support customized `className` and `id` on BootstrapTable.
> customized classes and id on BootstrapTable (#235)

- packages/react-bootstrap-table2-example/examples/row-selection/selection-no-data.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/props-resolver/column-resolver.js
- packages/react-bootstrap-table2/src/props-resolver/index.js
- packages/react-bootstrap-table2/test/props-resolver/index.test.js
* use the correct amount of cells when the first row is select
* storybook added for development, not necessary in docs
fixes react-bootstrap-table/react-bootstrap-table2#264
> noDataIndication

- packages/react-bootstrap-table2-filter/src/filter.js
- packages/react-bootstrap-table2/src/sort/wrapper.js
Fix textFilter() for Internet Explorer (includes() and find() are not supported) 
- replace includes() with indexOf() !== -1
- [includes() browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility)
- replace find() with for loop
- [find() browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility)
> Fix textFilter() for Internet Explorer (includes() and find() are not supported) 

- docs/README.md
- packages/react-bootstrap-table2-example/examples/sort/default-sort-direction.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/sort/wrapper.js
- packages/react-bootstrap-table2/src/store/index.js
- packages/react-bootstrap-table2/src/store/sort.js
- packages/react-bootstrap-table2/test/store/index.test.js
- packages/react-bootstrap-table2/test/store/sort.test.js
> allow to custom the default sort direction

- packages/react-bootstrap-table2/src/bootstrap-table.js
Let's say I need to add a 'table-responsive' class or another custom class.
The https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/317 can be closed
> Ability to add classes to the table wrapper

- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/test/cell.test.js
> fix the bool rendering issues in React

- packages/react-bootstrap-table2-example/examples/pagination/custom-pagination.js
- packages/react-bootstrap-table2-paginator/src/const.js
- packages/react-bootstrap-table2-paginator/src/pagination-total.js
- packages/react-bootstrap-table2-paginator/src/pagination.js
- packages/react-bootstrap-table2-paginator/src/wrapper.js
- packages/react-bootstrap-table2-paginator/test/wrapper.test.js
Putting back the ability to override the default pagination totals (like paginationShowsTotal in the original react-bootstrap-table).
> Adding custom pagination total

- packages/react-bootstrap-table2-paginator/src/wrapper.js
- packages/react-bootstrap-table2-paginator/test/wrapper.test.js
The issue:
When changing pages on a remote implementation with filters componentWillReceiveProps fires twice. It fires once on the initial page change click, and again when the updated data is received. Therefore, when data (2nd time it fires) is received the current logic believes a page hasn't been selected. It subsequently sets the current page to the start index value incorrectly.
For example, with my remote implementation: if I select page 4, the second time pagination componentWillReceiveProps fires, I end up with page 1 being selected whilst I have received page 4 data.
> Prevent remote pagination from setting the page incorrectly

- packages/react-bootstrap-table2-filter/src/components/date.js
Fix for my issue  #423 
Commented out a check which caused the date filter to not update the table when the date or date comparator were cleared
Modified applyFilter in date.js so that it doesn't try to parse an
Invalid Date. It was parsing an empty string, which caused it to pass
through an invalid date to onFilter, and this wasn't being checked for
properly by the onFilter function. It now checks for the empty string
and passes in null, which is what the onFilter function was actually
checking for
> Resolved issues with Date Filter to make its behavior the same as Number Filter

- packages/react-bootstrap-table2-paginator/src/page.js
- packages/react-bootstrap-table2-paginator/test/page.test.js
Local pagination aligning returns start page when eg editing cell locally. This results in state change, too. Not really getting the purpose of the original idea. Please consider this modification. It only checks if page fits in the data size range. As I saw, this alignment only affects local pagination, not remote.
> Copas2 patch pagination

- docs/development.md
Hi there 👋 while playing around with the project, I noticed a small typo in the setup guide. There doesn't appear to be an open issue for it (please let me know if I should create one and reference this one).  
While watching `npm install` run, I noticed that the step for running `lerna` was part of a `postinstall` step:
```
postinstall
lerna bootstrap
```
which led me to removing that as well.  If it's still necessary, I'd be happy to restore it :-)
Changes:
- Update directory name that's created after cloning the project
- Remove lerna bootstrap step (appears to be run as a postinstall step in npm scripts)
> Update development.md with git clone directory

- packages/react-bootstrap-table2-filter/src/components/select.js
You swapped `value` and `label` in the [fix](https://github.com/react-bootstrap-table/react-bootstrap-table2/commit/98a04a57100a2cd9f990ae540e30f16d53a541fa#diff-bd09df04374959a2d6a934ea8059f1bcR89) for #641.
This corrects that swap.
You will also want to update your [docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Preserved%20Option%20Order%20on%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) as it currently uses a swapped example:
```js
const selectOptions = [
{ label: 0, value: 'good' },
{ label: 1, value: 'Bad' },
{ label: 2, value: 'unknown' }
];
```
> fix #641 typo

- packages/react-bootstrap-table2/src/bootstrap-table.js
> Condensed now takes bootstrap4 into consideration

- packages/react-bootstrap-table2/src/header.js
Since we've supported `bootstrap4` by `context` api, the props becomes redundant and unnecessary.
> Remove unnecessary props 'bootstrap4'

- packages/react-bootstrap-table2-example/examples/cell-edit/custom-editor-table.js
The example code has a typo, the actual code right above is correct.
> Fix typo in custom-editor doc example code

- packages/react-bootstrap-table2-example/examples/footer/column-align-table.js
- packages/react-bootstrap-table2-example/examples/footer/column-attrs-table.js
- packages/react-bootstrap-table2-example/examples/footer/column-class-table.js
- packages/react-bootstrap-table2-example/examples/footer/column-event-table.js
- packages/react-bootstrap-table2-example/examples/footer/column-format-table.js
- packages/react-bootstrap-table2-example/examples/footer/column-style-table.js
- packages/react-bootstrap-table2-example/examples/footer/column-title-table.js
- packages/react-bootstrap-table2-example/examples/footer/footer-class-table.js
- packages/react-bootstrap-table2-example/examples/footer/function-footer.js
- packages/react-bootstrap-table2-example/examples/footer/simple-footer.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-example/stories/stylesheet/columns/_index.scss
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/footer-cell.js
- packages/react-bootstrap-table2/src/footer.js
- packages/react-bootstrap-table2/test/footer.test.js
Fix #2 
Trying to add a footer for the table, this is a early PR just to ask if I'm in the right track.
> [WIP] Add table footer

- packages/react-bootstrap-table2-toolkit/src/search/SearchBar.js
```
index.js:1446 Warning: Failed prop type: Invalid prop `tableId` of type `number` supplied to `SearchBar`, expected `string`.
```
btw it seems like `tableId` is never populated with toolkit provider. At least couldn't find it: https://github.com/react-bootstrap-table/react-bootstrap-table2/search?q=tableId&unscoped_q=tableId
> Fix default prop tableId for SearchBar

- packages/react-bootstrap-table2-toolkit/README.md
- packages/react-bootstrap-table2-toolkit/context.js
- packages/react-bootstrap-table2-toolkit/src/csv/exporter.js
- packages/react-bootstrap-table2-toolkit/src/op/csv.js
> Add prop to allow the csv/exporter.js to allow an override to the blob type.

- docs/README.md
- packages/react-bootstrap-table2-example/examples/loading-overlay/table-overlay.js
Why?
Current example `overlayFactory(spinner: true, background: 'red')` does not work.
Solution:
Update example of usage `overlayFactory` according to "react-loading-overlay" [documentation](https://github.com/derrickpelletier/react-loading-overlay#styles-with-emotion-woman_singer) _Custom overlay background (extending base styles)_.
The correct format if:
```js
overlayFactory({
spinner: true,
styles: {
overlay: base => ({ ...base, background: 'rgba(255, 0, 0, 0.5)' })
}
})
```
> Update README, overlayFactory example

- docs/row-selection.md
- packages/react-bootstrap-table2-example/examples/row-selection/non-selectable-rows-class.js
- packages/react-bootstrap-table2-example/examples/row-selection/non-selectable-rows-style.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/row-selection/row-consumer.js
Improve #1135 
Improves the solution provided on issue # 1135, instead of using a workaround its possible to provide the `nonSelectableStyle` and `nonSelectableClasses` directly
```jsx
const selectRow = {
mode: 'checkbox',
nonSelectable: [1, 3 ,5],
nonSelectableStyle: { backgroundColor: 'gray' }
};
```
```jsx
const selectRow = {
mode: 'checkbox',
nonSelectable: [1, 3 ,5],
nonSelectableClasses: 'my-class'
};
> Set custom class or style for disabled/non-selectable. [Improve #1135]

- packages/react-bootstrap-table2/package.json
This is an addition to #1107, which missed the version number in this file. So this is still causing issues when using yarn with webpacker.
> Avoid exact version lock for classnames package 

- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/test/header-cell.test.js
- Adds onKeyUp event to aid in ADA compliance
Needed for keyboard navigation. Current functionality does not allow a user to sort with their keyboard,
Still doesn't call out ascending or descending order on a screen reader but I felt like this was a start.
#1238
> Adds onKeyUp event to header for sort

- packages/react-bootstrap-table2-filter/src/filter.js
~~I can't install dependencies successfully on my local to run tests; also, it seems CI doesn't work either.~~
~~I will just open this as draft PR first.~~
With using Node 7, I can install dependencies successfully now but it seems we have several failures in current master.
Other than existing failures, this PR is ready for review.
> Refactor a little for filter.js in react-bootstrap-table2-filter

- docs/README.md
I added more info to the descriptions of the keyField and data props of
the Table component. I also added an example of what these properties
might look like for a sample dataset.
I couldn't find any info in the documentation about how the data should be formatted or what that should look like (I found a medium post that explained it well), and I had to read the source code to understand what the keyField was for. I think having better descriptions of these props in the documentation will be helpful to users.
> Update keyField/data props Documentation

- packages/react-bootstrap-table2-toolkit/README.md
- packages/react-bootstrap-table2-toolkit/src/search/SearchBar.js
We needed to customize the aria-label text, so I went in to make it configurable. I noticed that between the sr text above and the aria-label on the input itself, there were essentially two labels for the input. This change replaces aria-label with aria-labelledby and makes the sr text configurable.
> Minor changes to aria label and screen reader text

- packages/react-bootstrap-table2/src/row-selection/selection-cell.js
- packages/react-bootstrap-table2/test/row-selection/selection-cell.test.js
Re-opening #1139 to correct the branches.
Original PR text:
I was writing a custom renderer for the selection cell in order to add a label to the input for screen readers. But I realized that the `rowIndex` being passed in cannot reliably be used to get the row data, since filtering and sorting affect it.
This change merely adds the `rowKey` as an additional param to custom `selectionRenderer` functions.
> Add rowKey to selection cell renderer

- packages/react-bootstrap-table2/src/utils.js
- packages/react-bootstrap-table2/test/utils.test.js
Due to splitting object field by dot (.), when an user provides a data
which key has a dot, it will cause an issue for an `undefined` data
which looks like not rendered.
So, to solve this, we should try to get the object value from the key
first. If it's not defined or null, then we will try to do the original
recursive way to get value.
Fix #1381
> Get value from key first; if not existing, try recursive get
