react-bootstrap-table/react-bootstrap-table2

- .gitignore
- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/src/props-resolver/column-resolver.js
- packages/react-bootstrap-table2/src/props-resolver/index.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/test/body.test.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
- packages/react-bootstrap-table2/test/cell.test.js
- packages/react-bootstrap-table2/test/header-cell.test.js
- packages/react-bootstrap-table2/test/header.test.js
- packages/react-bootstrap-table2/test/row.test.js
> Bootstrap table base

- package.json
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
> Implement striped, hover, condensed and bordered

- packages/react-bootstrap-table2-example/src/index.js
- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/test/cell.test.js
- packages/react-bootstrap-table2/test/header-cell.test.js
Implement #21 
How to enable title on cell(header & body)
For Body Cell
```js
column.title = true  // default will show cell value as title
column.title = function(cell, row, colIndex) {  // customizable
return 'something';
}
```
For Header Cell
```js
column.headerTitle = true  // default will show column.text as default title
column.headerTitle = function(column, colIndex) {  // customizable
return 'something';
}
```
> Implement column title

- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/test/cell.test.js
Implement #23 
How to use?
```js
column.events.onClick = e => {
// do anything here
}
```
> Implement event hooks for column

- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/test/cell.test.js
- packages/react-bootstrap-table2/test/header-cell.test.js
Implement #24 
How ?
For Body Cell
```js
column.align = 'center'
column.align = function(cell, row, colIndex) {  // customizable
return 'center';
}
```
For Header Cell
```js
column.headerAlign ='center'
column.headerAlign = function(column, colIndex) {  // customizable
return 'center';
}
```
> Implement align on header an body cell

- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/test/header-cell.test.js
Implement #29
```js
column.headerEvents.onClick = e => {
// do anything here
}
```
> implement event hooks on header column

- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/props-resolver/column-resolver.js
- packages/react-bootstrap-table2/src/props-resolver/index.js
- packages/react-bootstrap-table2/src/store/base.js
> Refactoring props resolver and internal store

- package.json
- packages/react-bootstrap-table2-example/.storybook/webpack.config.js
- packages/react-bootstrap-table2-example/examples/basic/no-data-table.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/props-resolver/column-resolver.js
- packages/react-bootstrap-table2/src/props-resolver/index.js
- packages/react-bootstrap-table2/src/row-section.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/style/react-bootstrap-table.scss
- packages/react-bootstrap-table2/test/body.test.js
- packages/react-bootstrap-table2/test/row-section.test.js
- webpack.config.babel.js
- yarn.lock
fix https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/40
> Implement noDataIndication prop

- packages/react-bootstrap-table2-example/examples/basic/borderless-table.js
- packages/react-bootstrap-table2-example/examples/basic/index.js
- packages/react-bootstrap-table2-example/examples/basic/no-data-table.js
- packages/react-bootstrap-table2-example/examples/basic/striped-hover-condensed-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-align-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-class-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-event-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-format-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-format-with-extra-data-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-hidden-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-style-table.js
- packages/react-bootstrap-table2-example/examples/columns/column-title-table.js
- packages/react-bootstrap-table2-example/examples/columns/nested-data-table.js
- packages/react-bootstrap-table2-example/examples/header-columns/column-align-table.js
- packages/react-bootstrap-table2-example/examples/header-columns/column-class-table.js
- packages/react-bootstrap-table2-example/examples/header-columns/column-event-table.js
- packages/react-bootstrap-table2-example/examples/header-columns/column-format-table.js
- packages/react-bootstrap-table2-example/examples/header-columns/column-style-table.js
- packages/react-bootstrap-table2-example/examples/header-columns/column-title-table.js
- packages/react-bootstrap-table2-example/src/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/index.js
- packages/react-bootstrap-table2/src/props-resolver/index.js
- packages/react-bootstrap-table2/src/stateful-layer.js
@Chun-MingChen something change here
1. I add a HOC for `BootstrapTable` which is responsible for changing data(update/insert/delete)
2. `src/index.js` now export `BootstrapTable` and `BootstrapTableful`
You can imagine `BootstrapTable` is a pure/stateless component, and `BootstrapTableful` is stateful component which will help you operate data changing internally.
> Implement stateful layer

- docs/columns.md
- packages/react-bootstrap-table2-example/examples/sort/custom-sort-table.js
- packages/react-bootstrap-table2-example/examples/sort/enable-sort-table.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/const.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/src/sort-caret.js
- packages/react-bootstrap-table2/src/sort-symbol.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/src/store/sort.js
- packages/react-bootstrap-table2/src/utils.js
- packages/react-bootstrap-table2/style/react-bootstrap-table.scss
- packages/react-bootstrap-table2/test/header-cell.test.js
- packages/react-bootstrap-table2/test/header.test.js
- packages/react-bootstrap-table2/test/sort-caret.test.js
- packages/react-bootstrap-table2/test/sort-symbol.test.js
- packages/react-bootstrap-table2/test/store/base.test.js
- packages/react-bootstrap-table2/test/store/sort.test.js
> implement column sort

- packages/react-bootstrap-table2-example/examples/basic/table-with-caption.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/caption.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
Add tableCaption prop, which can be a component / string
Add simple test and an example to Storybook
> Implement basic usage of table <caption> element

- docs/columns.md
- packages/react-bootstrap-table2-example/examples/cell-edit/cell-edit-class-table.js
- packages/react-bootstrap-table2-example/examples/cell-edit/cell-edit-style-table.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-example/stories/stylesheet/cell-edit/_index.scss
- packages/react-bootstrap-table2-example/stories/stylesheet/storybook.scss
- packages/react-bootstrap-table2/src/cell-edit/editing-cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/test/cell-edit/editing-cell.test.js
- packages/react-bootstrap-table2/test/row.test.js
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/101
> Implement cell editor style

- docs/row-selection.md
- packages/react-bootstrap-table2-example/examples/row-selection/non-selectable-rows.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/row-selection/selection-cell.js
- packages/react-bootstrap-table2/src/row-selection/wrapper.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/test/row-selection/selection-cell.test.js
- packages/react-bootstrap-table2/test/row.test.js
- packages/react-bootstrap-table2/test/store/base.test.js
#106 
@Chun-MingChen  https://github.com/react-bootstrap-table/react-bootstrap-table2/commit/9f3d7ef4ba674e4a95b8c1166ac5ddd94cf90306
> Implement selectRow.nonSelectable

- docs/row-selection.md
- packages/react-bootstrap-table2-example/examples/row-selection/selection-bgcolor.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/test/body.test.js
> Implement selection background color

- CONTRIBUTING.md
- docs/README.md
Hi Allen,
Sorry for this super late PR. Life has been very busy these days.
I've made several tweaks and hoping that I didn't change the original meaning that you're
trying to express in the doc.
Cheers!
> Improve CONTRIBUTING doc

- docs/row-selection.md
- packages/react-bootstrap-table2-example/examples/row-selection/selection-hooks.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/row-selection/selection-cell.js
- packages/react-bootstrap-table2/src/row-selection/wrapper.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/test/body.test.js
- packages/react-bootstrap-table2/test/row-selection/selection-cell.test.js
- packages/react-bootstrap-table2/test/row-selection/wrapper.test.js
- packages/react-bootstrap-table2/test/row.test.js
- packages/react-bootstrap-table2/test/store/base.test.js
> Implement selectRow.onSelect and selectRow.onSelectAll

- docs/row-selection.md
- packages/react-bootstrap-table2-example/examples/row-selection/hide-selection-column.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/test/header.test.js
- packages/react-bootstrap-table2/test/row.test.js
> Implement hiding selection column

- docs/README.md
- packages/react-bootstrap-table2-example/examples/sort/default-sort-table.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/sort/wrapper.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/test/sort/wrapper.test.js
- packages/react-bootstrap-table2/test/store/base.test.js
> Implement default sort

- docs/README.md
- packages/react-bootstrap-table2-example/examples/rows/row-class.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-example/stories/stylesheet/rows/_index.scss
- packages/react-bootstrap-table2-example/stories/stylesheet/storybook.scss
- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/test/body.test.js
> Implement rowClasses

- docs/README.md
- packages/react-bootstrap-table2-example/examples/rows/row-event.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/test/body.test.js
- packages/react-bootstrap-table2/test/row.test.js
> Implement custom row events

- packages/react-bootstrap-table2-example/examples/pagination/remote-pagination.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-paginator/src/wrapper.js
- packages/react-bootstrap-table2-paginator/test/wrapper.test.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/container.js
- packages/react-bootstrap-table2/src/store/base.js
- packages/react-bootstrap-table2/src/table-factory.js
- packages/react-bootstrap-table2/test/container.test.js
- packages/react-bootstrap-table2/test/store/base.test.js
fix https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/140
I'll open nother PR to implement loading overlay.
> Implement remote pagination

- packages/react-bootstrap-table2/src/sort/wrapper.js
- packages/react-bootstrap-table2/src/table-factory.js
Root cause is I wrap wrong HOC for `SortWrapper`
> Fix the pagination will disapper when enable sort

- docs/README.md
Hi @AllenFang,
This is a tiny patch for pagination document and content as the following. Please take a look, thanks :)
* pagination hooks
* required props for remote mode
> [Document] patch for pagination

- docs/columns.md
- packages/react-bootstrap-table2-example/examples/header-columns/column-format-filter-sort-table.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/style/react-bootstrap-table.scss
- packages/react-bootstrap-table2/test/header-cell.test.js
> headerFormatter is able to custom whole the content of header cell

- docs/README.md
- packages/react-bootstrap-table2-example/examples/remote/remote-sort.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/props-resolver/remote-resolver.js
- packages/react-bootstrap-table2/src/sort/wrapper.js
- packages/react-bootstrap-table2/src/store/index.js
- packages/react-bootstrap-table2/test/props-resolver/remote-resolver.test.js
- packages/react-bootstrap-table2/test/sort/wrapper.test.js
- packages/react-bootstrap-table2/test/store/index.test.js
> implement remote sorting

- packages/react-bootstrap-table2-example/examples/column-filter/text-filter-caseSensitive.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-filter/README.md
- packages/react-bootstrap-table2-filter/src/components/select.js
- packages/react-bootstrap-table2-filter/src/filter.js
- packages/react-bootstrap-table2-filter/test/filter.test.js
refine #190 
* Text Filter default will be insensitive, actually, in `react-bootstrap-table`, the text filter is case insensitive.
* Support `caseSensitive` for TextFilter
> refine caseSensitive for filter

- docs/columns.md
- docs/migration.md
- packages/react-bootstrap-table2-example/examples/sort/sort-events.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/sort/wrapper.js
- packages/react-bootstrap-table2/test/sort/wrapper.test.js
> Support sort event listener

- packages/react-bootstrap-table2/src/bootstrap-table.js
> Fixes #186

- docs/row-selection.md
- packages/react-bootstrap-table2-example/examples/row-selection/default-select.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/row-selection/wrapper.js
- packages/react-bootstrap-table2/test/row-selection/wrapper.test.js
fix https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/224
> Implement default selection

- packages/react-bootstrap-table2/src/cell.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/src/row.js
- packages/react-bootstrap-table2/test/cell.test.js
- packages/react-bootstrap-table2/test/header-cell.test.js
- packages/react-bootstrap-table2/test/header.test.js
- packages/react-bootstrap-table2/test/row.test.js
> Fixed #237

- packages/react-bootstrap-table2-example/examples/pagination/custom-pagination.js
- packages/react-bootstrap-table2-paginator/src/page-resolver.js
- packages/react-bootstrap-table2-paginator/src/pagination-total.js
- packages/react-bootstrap-table2-paginator/src/pagination.js
- packages/react-bootstrap-table2-paginator/src/wrapper.js
- packages/react-bootstrap-table2-paginator/test/page-resolver.test.js
- packages/react-bootstrap-table2-paginator/test/wrapper.test.js
> Implement pagination total

- packages/react-bootstrap-table2/src/row-event-delegater.js
> Add onDoubleClick on rowEvents props

- docs/migration.md
- packages/react-bootstrap-table2-example/examples/column-filter/advance-custom-filter.js
- packages/react-bootstrap-table2-example/examples/column-filter/custom-filter.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-filter/README.md
- packages/react-bootstrap-table2-filter/index.js
- packages/react-bootstrap-table2-filter/src/wrapper.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/header-cell.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/test/header-cell.test.js
> Implement custom filter

- packages/react-bootstrap-table2-example/examples/column-filter/multi-select-filter-default-value.js
- packages/react-bootstrap-table2-example/examples/column-filter/multi-select-filter.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-filter/index.js
- packages/react-bootstrap-table2-filter/src/components/multiselect.js
- packages/react-bootstrap-table2-filter/src/const.js
- packages/react-bootstrap-table2-filter/src/filter.js
- packages/react-bootstrap-table2-filter/src/wrapper.js
- packages/react-bootstrap-table2-filter/test/components/multiselect.test.js
#199 
Recreate branch from #429
> Multiselectv2

- packages/react-bootstrap-table2/src/row.js
> Bugfix #471

- packages/react-bootstrap-table2/src/row-event-delegater.js
This should has onContextMenu event to handler. Otherwise I have to go around to handle right click.
> add onContextMenu event on row event handler

- docs/cell-edit.md
- packages/react-bootstrap-table2-editor/src/editing-cell.js
- packages/react-bootstrap-table2-editor/src/text-editor.js
- packages/react-bootstrap-table2-editor/src/textarea-editor.js
- packages/react-bootstrap-table2-example/examples/cell-edit/auto-select-text-input-table.js
- packages/react-bootstrap-table2-example/stories/index.js
> Implement auto select input text when editing cell

- packages/react-bootstrap-table2/src/contexts/selection-context.js
- packages/react-bootstrap-table2/test/contexts/selection-context.test.js
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/538
> fix wrong result pass to selectRow.onSelectAll when isSelect argument is false

- packages/react-bootstrap-table2-example/examples/search/default-search.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-toolkit/README.md
- packages/react-bootstrap-table2-toolkit/context.js
- packages/react-bootstrap-table2-toolkit/src/search/SearchBar.js
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/541
> Support default search

- docs/row-expand.md
- packages/react-bootstrap-table2-example/examples/row-expand/expand-only-one.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/contexts/row-expand-context.js
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/564
> Implement expandRow.onlyOneExpanding

- packages/react-bootstrap-table2-filter/README.md
MULTISELECT type is missing in filter type list
> Add MULTISELECT filter type in filter doc

- packages/react-bootstrap-table2-paginator/src/pagination-total.js
> fix #654 #611

- docs/about.md
- docs/getting-started.md
Just cleaning up some of the wording & typos in the documentation
> Some small documentation typos

- docs/about.md
This is a proposed rewrite of the about page
> Rewrite about page

- packages/react-bootstrap-table2-toolkit/src/op/csv.js
- packages/react-bootstrap-table2-toolkit/statelessOp.js
- packages/react-bootstrap-table2/src/bootstrap-table.js
- packages/react-bootstrap-table2/src/contexts/index.js
- packages/react-bootstrap-table2/src/contexts/selection-context.js
- packages/react-bootstrap-table2/test/bootstrap-table.test.js
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/620
#734
> fix #734, fix #620

- packages/react-bootstrap-table2-filter/src/components/date.js
> Allow null date when clearing date filter with getFilter function

- docs/migration.md
- packages/react-bootstrap-table2-example/examples/bootstrap4/column-toggle.js
- packages/react-bootstrap-table2-example/examples/column-toggle/custom-toggle-list.js
- packages/react-bootstrap-table2-example/examples/column-toggle/default-visibility.js
- packages/react-bootstrap-table2-example/examples/column-toggle/index.js
- packages/react-bootstrap-table2-example/examples/column-toggle/styling-toggle-list.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-toolkit/README.md
- packages/react-bootstrap-table2-toolkit/context.js
- packages/react-bootstrap-table2-toolkit/index.js
- packages/react-bootstrap-table2-toolkit/src/column-toggle/index.js
- packages/react-bootstrap-table2-toolkit/src/column-toggle/toggle-list.js
- packages/react-bootstrap-table2/src/contexts/column-context.js
- packages/react-bootstrap-table2/src/contexts/index.js
- packages/react-bootstrap-table2/src/footer.js
- packages/react-bootstrap-table2/src/header.js
- packages/react-bootstrap-table2/src/row/row-pure-content.js
- packages/react-bootstrap-table2/test/contexts/column-context.test.js
- packages/react-bootstrap-table2/test/contexts/index.test.js
- packages/react-bootstrap-table2/test/header.test.js
- packages/react-bootstrap-table2/test/row/row-pure-content.test.js
> Implement Column Toggle(723)

- package.json
- packages/react-bootstrap-table2-example/examples/pagination/standalone-pagination-total.js
- packages/react-bootstrap-table2-example/stories/index.js
- packages/react-bootstrap-table2-paginator/README.md
- packages/react-bootstrap-table2-paginator/index.js
- packages/react-bootstrap-table2-paginator/src/pagination-total-adapter.js
- packages/react-bootstrap-table2-paginator/src/pagination-total-standalone.js
- packages/react-bootstrap-table2-paginator/src/pagination-total.js
- packages/react-bootstrap-table2-paginator/src/pagination.js
- packages/react-bootstrap-table2-paginator/src/size-per-page-dropdown-adapter.js
- packages/react-bootstrap-table2-paginator/test/pagination-total-adapter.test.js
- packages/react-bootstrap-table2-paginator/test/pagination.test.js
> Implement PaginationTotalStandalone

- packages/react-bootstrap-table2/src/body.js
- packages/react-bootstrap-table2/src/row-expand/row-consumer.js
> Expanded row column span does not update

- packages/react-bootstrap-table2/package.json
- packages/react-bootstrap-table2/src/contexts/row-expand-context.js
- packages/react-bootstrap-table2/src/row-expand/expand-row.js
- packages/react-bootstrap-table2/src/row-expand/row-consumer.js
- packages/react-bootstrap-table2/style/react-bootstrap-table2.scss
#728 
There are currently 2 limitations:
- ~~Programmatic expand management isn't animated yet~~
- ~~The bottom and top padding inside the expansion have to be removed for a smooth animation, we can 
either keep it this way and the user can add his own padding, or we can add an extra div inside the 
animation div with the padding~~
> [WIP] Animate row expansion

- docs/pagination-props.md
Fix prop name in document.
https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/973ece8b3967ad6c8c3c7cc236255cadc4e0f60e/packages/react-bootstrap-table2-paginator/src/page-button.js#L23
> Fix prop name disable to disabled

- packages/react-bootstrap-table2-example/examples/row-expand/expand-only-one.js
You missed 'onlyOneExpanding: true' in the source code.
> Added missed attribute

- packages/react-bootstrap-table2/src/header-cell.js
> set tabindex to 0 for table headers

- packages/react-bootstrap-table2-editor/README.md
- packages/react-bootstrap-table2-editor/src/dropdown-editor.js
- packages/react-bootstrap-table2-example/examples/cell-edit/dropdown-editor-with-dynamic-options-table.js
- packages/react-bootstrap-table2-example/stories/index.js
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/945
> implement #945

- packages/react-bootstrap-table2-example/stories/index.js
Fromatted Value => Formatted Value
> Fix typo in storybook

- package.json
> Avoid exact version lock for classnames package

- packages/react-bootstrap-table2-editor/package.json
- packages/react-bootstrap-table2-example/package.json
- packages/react-bootstrap-table2-filter/package.json
- packages/react-bootstrap-table2-paginator/package.json
- packages/react-bootstrap-table2-toolkit/package.json
- packages/react-bootstrap-table2/package.json
- packages/react-bootstrap-table2/src/contexts/index.js
> Fix `onSort is not a function` issue
